version: "3"

services:
  frontend:
    build: ./dockers/angular
    volumes:
      - ./frontend/:/app/
    ports:
      - "${FRONTEND_SERVER_PORT}:4200"
  app:
    image: webdevops/php-apache-dev:7.2
    user: "application"
    environment:
      - XDEBUG_REMOTE_AUTOSTART=On
      - XDEBUG_PROFILER_ENABLE=On
      - XDEBUG_REMOTE_HOST="${HOST_IP}"
      - XDEBUG_REMOTE_PORT="${DEBUG_PORT}"
      - PHP_DEBUGGER=xdebug
      - WEB_DOCUMENT_ROOT=/app/public
    ports:
     - "${BACKEND_PORT}:80"
    volumes:
      - ./backend/:/app/
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
    ports:
     - "${DB_PORT}:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=root
    restart: always
    ports:
     - "${PHPMYADMIN}:80"
    volumes:
     - /sessions
